spring:
  # 邮箱配置
  mail:
    host: smtp.163.com #发送邮件服务器
    username: lagouDemo@163.com #发送邮件的邮箱地址
    password: DZGAMFOANHHSBGHF #客户端授权码，不是邮箱密码,网易的是自己设置的
    properties.mail.smtp.port: 994 #465或者994
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lagou?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: lagoudemo
    password: lagoudemo2021

ip-filter:
  window-minutes: 1
  max-request-times: 100
